[package]
name = "tmidl-json"
version = "0.1.0"
edition = "2018"

[dependencies]
codespan-reporting = "0.11.1"
serde = { version = "1.0.130", features = ["derive"] }
serde_json = "1.0.68"
tmidl-sys = { path = "../tmidl-sys" }
