/* A packrat parser generated by PackCC 1.5.1 */

#ifndef PCC_INCLUDED_GENERATED_H
#define PCC_INCLUDED_GENERATED_H

#include "auxil.h"
#ifdef __cplusplus
extern "C" {
#endif

typedef struct pcc_context_tag pcc_context_t;

pcc_context_t *pcc_create(pcc_auxil_o *auxil);
int pcc_parse(pcc_context_t *ctx, int *ret);
void pcc_destroy(pcc_context_t *ctx);

#ifdef __cplusplus
}
#endif

#endif /* !PCC_INCLUDED_GENERATED_H */
